apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-review-ingress
  namespace: book-review-dev
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        # ðŸ”¹ Backend API
        - path: /api(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: book-review-backend
              port:
                number: 3001

        # ðŸ”¹ Next.js static assets
        - path: /_next(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: book-review-frontend
              port:
                number: 3000

        # ðŸ”¹ Frontend pages
        - path: /(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: book-review-frontend
              port:
                number: 3000
