apiVersion: v1
kind: ConfigMap
metadata:
  name: book-review-config
  namespace: book-review-dev
  labels:
    app: book-review
data:
  backend_api_url: "http://app.berryexcel.online/api"  # full URL
  database_host: "cloudproj-dev-mysql-01b0dd.mysql.database.azure.com"
  database_port: "3306"
  database_name: "book_review_db"
  allowed_origins: "http://localhost:8080,http://app.berryexcel.online"
