apiVersion: v1
kind: Service
metadata:
  name: book-review-frontend
  namespace: book-review-dev
  labels:
    app: book-review
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: book-review
    component: frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
